### ISSUE TITLE
Issue with Grille recipe w/o Basic Materials

### ISSUE THREAD

**Issue by ghost** [mt-mods/new_campfire#4]
The recipe for the Metal Grille without Basic Materials don't work, if I click on the Grille to see the recipe, it shows no recipe at all.

**Comment by Niklp09** [comment]
Fixed in https://github.com/mt-mods/new_campfire/commit/fb2d38defebd18d59d15a0ed31598d8c6d2f2142

(Note: The wrong steel ingot itemstring was already in https://github.com/mt-mods/new_campfire/pull/2 present)

**Comment by ghost** [comment]
Thank you.
